services:
  mongodb: # 이름 설정 (자유)
    image: mongo # ' '를 이용하여 이미지 이름 명시
    # --rm이나 -d 옵션을 따로 설정하지 않아도 됨
    volumes: # docker-compose.yaml을 기준으로 상대경로 사용 가능
    # volume은 밑에 다시 명시 (최상위)
      - data:/data/db
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=value
    #   - MONGO_INITDB_ROOT_PASSWORD=value

    # docker compose는 자동으로 network를 생성 및 적용해줌
    # networks:
    #   - goals-net

  backend:
    # Build
    build:
      context: ./backend
      dockerfile: Dockerfile
    # Ports
    ports:
      - 80:80
    # Network
    # networks:
    #   - goals-net
    # Volumes
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    # Depends On
    depends_on:
      - mongodb # 서비스 이름이어야 함
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src

    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  logs: